### ISSUE TITLE
2FA Google Messages - Unable connect - No QR URL in log

### ISSUE THREAD

**Issue by chklff** [Voyz/ibeam#124]
**Describe the bug**
Ibeam starts and picks the type of the 2FA handler from env.list but it stuck at some point where logs should provide the URL for the QR code that has to be scanned in the android app.

**To Reproduce**
1. Run the Ibeam
2. Wait until the @ Factor Authentification will start 
3. See the system is unable to provide the URL for QR scanner in the Google Messenger app

**Expected behavior**
URL provided in the log, scanned, Messenger connect, Ibeam unable to capture 2FA SMS

**Environment**
IBeam version: 0.4.3
Docker image or standalone: Docker Image
Python version (standalone users only): 
OS: Ubuntu 22.10

**Additional context**
It looks like an issue with the Selenium driver 

When I use Ibeam with Fingerprint/IBRK app authentication instead SMS everything works fine, besides the periodical session ends and manual reauthorization via the confirmation in IBRK app

**Suggest a Fix**
Please check the google_msg_handler.py from lines 55 to 69
Lines 64 to 67 should generate a QR URL in the log for the scanner as I understand
Selenium Session info: headless chrome=90.0.4430.212

Please see the log attached from lines 34 to 65
[ibeam_log.txt](https://github.com/Voyz/ibeam/files/10407418/ibeam_log.txt)

**Comment by Voyz** [comment]
Hey @chklff thanks for reporting the issue in detail 👍

It seems that the Google Messages page is not loaded correctly. Could you try to manually access the `https://messages.google.com/web` from the server IBeam is running on and check that once the page loads any of the following are present:

- qr-code (class)
- .text-content.unread .snippet-text (class)
- Your requested authentication code (text)

These are what IBeam checks for, and in absence of which it times out.

Also, try to run IBeam in Debug mode and provide the output it produces: https://github.com/Voyz/ibeam/wiki/IBeam-Configuration#debugging

**Comment by Chekaloff** [comment]
@Voyz Do you know by any chance the approximate curl I can execute in Ibeam shell, because "manually access" remote Ubuntu server in this case should give a totally different result... 

this for example curl from Cromium on my mac 

curl 'https://messages.google.com/web/' \
  -H 'Upgrade-Insecure-Requests: 1' \
  -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.5359.98 Safari/537.36' \
  -H 'sec-ch-ua: "Not?A_Brand";v="8", "Chromium";v="108", "Sidekick";v="108"' \
  -H 'sec-ch-ua-arch: "arm"' \
  -H 'sec-ch-ua-bitness: "64"' \
  -H 'sec-ch-ua-full-version: "108.34.1.28996"' \
  -H 'sec-ch-ua-full-version-list: "Not?A_Brand";v="8.0.0.0", "Chromium";v="108.34.1.28996", "Sidekick";v="108.34.1.28996"' \
  -H 'sec-ch-ua-mobile: ?0' \
  -H 'sec-ch-ua-model: ""' \
  -H 'sec-ch-ua-platform: "macOS"' \
  -H 'sec-ch-ua-platform-version: "13.0.1"' \
  -H 'sec-ch-ua-wow64: ?0' \
  --compressed
  
  Thank you in advance!

**Comment by Chekaloff** [comment]
Ok got it, so what are my steps to manually access the https://messages.google.com/web? 
Do you mean connect to the Docker container using a remote desktop? What browser should I use to simulate the Selenium activity, looks like it should be Chrome 90? 
Thanks!

**Comment by Chekaloff** [comment]
Ok,it looks like Google renamed the QR class from `qr-code` to `bigger-qr-code`
Testings

**Comment by alquantica** [comment]
I've had the same issue today when using the GOOGLE_MSG input. No URL is returned to paste in my browser. What is the fix for this please? I have the latest IBeam installed with Docker. Screenshot attached.

![Capture.PNG](https://user-images.githubusercontent.com/89523298/216134688-69df88be-e641-4973-9a90-f13bd82ed20b.PNG)

**Comment by Voyz** [comment]
@alquantica can you try setting `IBEAM_GOOG_QR_CODE_CLASS` to `bigger-qr-code` and see if it helps?

**Comment by Voyz** [comment]
@alquantica I looked into the google messages handler a bit. Try `voyz/ibeam:0.4.4-rc3` and let me know if it's working for you. It should generate the link with the QR code in the output log.

**Comment by urielco** [comment]
Hi @Voyz, I also have the same bug of no QR code. I just tried the new 0.4.4 version and it fails in an earlier stage:
```
2023-04-17 12:23:10,364|I| No active sessions, logging in...
2023-04-17 12:23:28,126|E| Timeout reached when waiting for authentication. Consider increasing IBEAM_PAGE_LOAD_TIMEOUT. Error: "timeout: Timed out receiving message from renderer: 14.701
  (Session info: headless chrome=90.0.4430.212)" at   File "/srv/ibeam/src/authenticate.py", line 183, in authenticate_gateway    driver.get(base_url + var.ROUTE_AUTH)
2023-04-17 12:23:28,191|I| Authentication process failed
2023-04-17 12:23:28,197|I| Starting maintenance with interval 60 seconds
2023-04-17 12:24:28,297|I| No active sessions, logging in...
2023-04-17 12:24:46,377|E| Timeout reached when waiting for authentication. Consider increasing IBEAM_PAGE_LOAD_TIMEOUT. Error: "" at   File "/srv/ibeam/src/authenticate.py", line 187, in $uthenticate_gateway    WebDriverWait(driver, 15).until(user_name_present)
2023-04-17 12:24:46,430|I| Authentication process failed
...
```
Increasing IBEAM_PAGE_LOAD_TIMEOUT doesn't solve the problem. Has something else changed in this version?

**Comment by kashyappatel7** [comment]
i just pulled .4.4-rc4 and it works. I'm able to see the URL in the logs

**Comment by Voyz** [comment]
Closing as this is addressed with https://github.com/Voyz/ibeam/releases/tag/v0.4.4. Thanks for the contribution 😊
