### ISSUE TITLE
Webpage displayed "Client login succeeds" but not authenticated

### ISSUE THREAD

**Issue by chenkaiju** [Voyz/ibeam#142]
Hi @Voyz 

Thank you for providing such a good tool. But I encounter authentication problem. 
It keeps login success but not been authenticated.

![image](https://github.com/Voyz/ibeam/assets/4037429/cd70c8f9-7b1c-4ac6-be56-af1fa81d1784)

Do you have any suggestion? Thank you!

**Comment by Voyz** [comment]
Hey @chenkaiju thanks the kind words and for submitting your issue. Unfortunately, this 'authentication loop' is a problem that has been appearing for a very long time, and there is no currently known solution to it. It's been discussed in other issues, so feel free to search through for more information. One idea I've found most interesting was using VPN - I'm talking to IBKR about relevance of geolocation right now. The best idea would be for you to highlight the authentication problems with IBKR support so that they're aware of the problems we're facing. Given all that, I'm going to go ahead and close this issue, but thanks for submitting it in either case 👍

**Comment by Voyz** [comment]
hey @chenkaiju - there is a new WIP version `v0.5.0` of IBeam that introduces a new login logic, which should help reduce some of the issues we've been struggling with. 

Run [the most recent `voyz/ibeam:0.5.0-rc*`](https://hub.docker.com/r/voyz/ibeam/tags) tag of v0.5.0 and set `IBEAM_AUTHENTICATION_STRATEGY` to `B`. 

See #147 for more details and report any observations directly there. 

Thanks 🙏
