### ISSUE TITLE
The reauthenticate endpoint is deprecated

### ISSUE THREAD

**Issue by bfoz** [Voyz/ibeam#174]
I was looking through the [changelogs](https://ibkrcampus.com/ibkr-api-page/changelog/) on the new API portal and noticed this little tidbit:

![image](https://github.com/Voyz/ibeam/assets/65124/ce052992-0cae-44c6-9bf3-01a55c94e440)

Does this affect ibeam?

**Comment by Voyz** [comment]
I appreciate you reading through their changelog and spotting this 👏👏 

I've tried to swap it, but that new endpoint doesn't work for me when using it to _reauthenticate_: `https://localhost:5000/v1/api/iserver/auth/ssodh/init`.  

Originally with auth strategy B we'd call the `reauthenticate` when we'd find a running session that had troubles. The strategy was to call `logout` followed by `reauthenticate` which frequently helped to re-establish the connection. Now it seems that calling `auth/ssodh/init` after `logout` doesn't work - I'm getting either `410 gone` or `503`. 

So I suppose this isn't a 1-1 replacement, but we'd need to figure out a new authentication strategy to use it instead of `reauthenticate`. I'm leaving `reauthenticate` as it is for now.

----

Additionally, how would you interpret this sentence?

> After retrieving the access token and subsequent Live Session Token, customers can initialize their brokerage session with the ssodh/init endpoint.

Especially:

> [...] customers can initialize their brokerage session [...]

We're supposed to call this endpoint after logging in to initialise our session?

To validate that interpretation I've added a call to this new endpoint after we successfully log in. I've published `voyz/ibeam:0.5.2-rc2` Docker image with that modification - feel free to try it out.

**Comment by bfoz** [comment]
The documentation seems to be changing pretty quickly. The [Introduction](https://ibkrcampus.com/ibkr-api-page/webapi-doc/#introduction) now suggests that they're switching to OAuth 2.0 and that they're planning to have One API to rule them all. 

The section [Sessions in the Web API Copy Location](https://ibkrcampus.com/ibkr-api-page/webapi-doc/#sessions) describes a two-tier authentication system. A "read-only" tier that seems to be similar to what we're used to, and a "brokerage session" that is established after the first tier. I'm not sure if this is new, or simply newly documented, or I just didn't notice it before. 

Apparently all "/iserver" endpoints require a brokerage session, so that might be why you're having trouble reauthenticating. 

I'll try the new image. Thanks.

**Comment by Voyz** [comment]
Hey @bfoz thanks for this update. What you find seems to be consistent with this comment here: https://github.com/Voyz/ibeam/issues/150#issuecomment-2074334264

**Comment by Voyz** [comment]
I'm going to close this issue due to inactivity. Thanks for your contribution and please feel free to request a reopen if you'd like to continue the discussion 👍
