### ISSUE TITLE
Legacy versions of IBEAM

### ISSUE THREAD

**Issue by xjcarter** [Voyz/ibeam#187]
@Voyz
Is there a legacy version of IBeam that just connects to the IB Gateway without doing all the auto-fill magic?
I am still debugging this issue where I appear to have different element names for the web elements that show up on the
IBRK login/authentication page - so I if could see that directly, I think I can put this problem to bed.

Thanks!

**Comment by Voyz** [comment]
Thanks for your question @xjcarter 👍

There is no such version, but the functionality you look for has always been available. IBeam's entrypoint, the 'ibeam_starter.py` accepts a bunch of arguments. If it is run with `-s` option, it will do what you're looking for - only start the Gateway. 

In either case, if you need to manually authenticate with the Gateway running within IBeam, you can allow IBeam to start normally and fail the authentication. While it tries to re-authenticate the Gateway itself will remain open and you should be able to operate on it without any issues. I'd suggest this as the easiest way to start IBeam in order to have a Gateway open which you could manually authenticate with. Let me know if this works for you 👍

**Comment by xjcarter** [comment]
@Voyz 
Thanks Voy!
Yes that works - I was running into the 'Access Denied' roadblock because my local computer's IP address was not included in the 'ips/allow' section of the /srv/inputs/conf.yaml file:
```
ips:
  allow:
    - 10.*
    - 192.*
    - 131.216.*
    - 127.0.0.1
    - <my IP included here>
```

Thanks!

**Comment by Voyz** [comment]
Great, glad to hear you've figured it out 👏👏
