### ISSUE TITLE
Running ibeam for workflow services?

### ISSUE THREAD

**Issue by alex1999Tra** [Voyz/ibeam#40]
**Describe the feature**
Thanks for the package. It is super useful. Not sure if this would be an enhancement though.

I am trying to set up monthly auto investment (like what we did in retirement account). 
1. Currently I am using Python [schedule lib](https://schedule.readthedocs.io/en/stable/examples.html) to set up the recurring job. I want to evaluate some workflow service for better retry/error handling (e.g. AWS Step function, Cadence), is it feasible to use ibeam for the auth and how to do it? 
2. Is it recommended to turn off IBKR [`Secure Login System`](https://ndcdyn.interactivebrokers.com/en/software/am3/am.htm#am/settings/slsoptout.htm) for API auth? I have it enabled on my account. I need to manually approve the auth on my phone when the log in is required. I have `voyz/ibeam:0.4.0-rc1` running for more than 1 week. The gateway auth returned errors almost every other day (Sorry the ibeam auth logs were purged), and it would require re-login . I have to manually approve the auth on my phone. 

I am still very new to all IBKR API and Auth part.

**Comment by Voyz** [comment]
Hey @alex1999Tra welcome to IBeam and thanks for describing your workflow 👋

>  I want to evaluate some workflow service for better retry/error handling (e.g. AWS Step function, Cadence), is it feasible to use ibeam for the auth and how to do it?

Do I understand you correctly, that you wonder if IBeam can be used on a cloud-deployed instance? In such case yes, it's possible. I have a virtual instance with IBeam that I start and shut down several times a day and it functions as expected.

> Is it recommended to turn off IBKR Secure Login System for API auth? 

To be fair with you I wasn't aware this is possible. I'll let you know should I do so at some point. From what it looks like it would be a way to get over the 2FA - let me know how it goes if you give it a shot.

Otherwise, IBeam provides way to complete 2FA externally using 2FA handlers. See here for more: https://github.com/Voyz/ibeam/wiki/Two-Factor-Authentication

**Comment by JackD111** [comment]
You can create a new user linked to your main account. I believe it's restricted to only one user that runs alongside with the primary account holder. On that user you make sure to not activate 2FA because once it's enabled you can't turn it off. I'm using that second user in ibeam. This is also very nice because you can log in anytime in TWS or the client portal with your main user without taking away the session of the user logged into ibeam. My main user has 2FA enabled but the 2nd user has not 2FA enabled. Technically a security risk but it's the only way to properly run ibeam without any user interaction or google auth shananigans. What might make it secure but I haven't tried yet , is restricting the user to only be allowed to login from specific IPs which would than be my cloud machine running ibeam. That might be something worth investigating but I haven't bothered yet.

Read this article for more info about having a second user added to your account:
https://ibkr.info/article/1004

**Comment by Voyz** [comment]
@JackD111 that's a fantastic summary of doing it your way. Would you be interested in writing a short WiKi page for IBeam describing this method? I see plenty of questions about overcoming 2FA here, a lot of other users would find it very useful I bet! I'm happy to help you out with it

**Comment by alex1999Tra** [comment]
@JackD111 It sounds exactly what I need. 

Can you elaborate more what linked account you created? Do both accounts share the same username and pw?
<img width="1261" alt="Screen Shot 2021-11-15 at 3 44 21 PM" src="https://user-images.githubusercontent.com/31233533/141870377-09b9a515-7b77-435a-b0a1-5db2c4f8d1a6.png">

**Comment by JackD111** [comment]
@alex1999Tra I don't recognize the info from the screenshot. The new account will have its own username and password. Try logging into the client portal and go into "Account Settings". On the bottom right side, there is the following panel:
![image](https://user-images.githubusercontent.com/3951120/141954985-bb3e4c16-5f42-497d-87af-514f3ea5f859.png)
Click the cog and in the users list you should be able to setup the new user. It should be the same steps that are listed under "Background" in the ibkr article I've previously posted.
I think they either asked you to setup 2FA while setting up the user or after first login. Just make sure to cancel/deny so you don't end up with 2FA enabled.

**Comment by alex1999Tra** [comment]
A quick update, I followed @JackD111 suggestion: create a new user with the 2FA disabled. 
I created order placement workflow using AWS Step function. It has been running for a month without any re-auth issue. I can still log in the account with the primary user/pw without impacting the auto investment workflow.

**Comment by Voyz** [comment]
Great stuff @alex1999Tra thanks for following up. Glad to hear you've had a month of smooth runtime! Which image are you using?

**Comment by JackD111** [comment]
@Voyz I've been using `voyz/ibeam:0.4.0-rc1` pretty much since it's release. While that time i had a couple of problems. Two instances of those have been related to timeouts in the authentication. I enabled the option to save screenshots of login errors and even that threw timout errors in the driver. I assume that the IB api was just somehow impacted with problems but without a remote VNC or anything into the ibeam webdriver instance I couldnt investiage further. Both instances of the problem occured in one week so it was very likely an IB problem.

One other thing i noticed which happend rarely was related to the new logout functionaly. I get notifications when errors happen so I noticed it two times when my bot failed. Checking the ibeam containers showed, that because of an issue, ibeam decicded to logout and restart the IB gateway. This all was succesful and the log show that the session is active and connected. But the problem was than, that the `iserver/accounts` API started returning an empty `{}` response. I tried manually fixing it by sending the `iserver/reauthenticate` request but that didnt help. Checking my auth status showed following:
```
{
    "authenticated": true,
    "competing": true,
    "connected": true,
}
```

Notice how its showing that it's competing for the brokerage connection. This is probably due to the restart of the gateway. The only way i was able to solve the competing state was to send the `logout` API request and than immedatily after the sesion is authenticated again, send the `iserver/reauthenticate` request. Sending reauth right after a logout always worked and made the session not compete anymore. After this, the brokerage accounts api also returned accounts again properly.

I would suggest to slightly adjust the logout procedure. So after a logout, remember that we just logged out and on the first tickle call after logout we should check if `competing `is set to `true`. If so, immedtialy fire the reauth request. Maybe just shoot out the reauth request anyway after the first time auth completed after the logout.

**Comment by Voyz** [comment]
Hey @JackD111 that's a fantastic update, thank you for writing all of it up 👏

> Two instances of those have been related to timeouts in the authentication. I enabled the option to save screenshots of login errors and even that threw timout errors in the driver. I assume that the IB api was just somehow impacted with problems but without a remote VNC or anything into the ibeam webdriver instance I couldnt investiage further. Both instances of the problem occured in one week so it was very likely an IB problem.

If there's an issue starting up the web driver then indeed the screenshot cannot be made. In moments like these I run the Gateway on its own and try to see if the issue persists on my machine. If you could pass the logs (by default IBeam stores all logs in [a file](https://github.com/Voyz/ibeam/wiki/Inputs-And-Outputs#outputs-directory) on the container) we could try looking into what caused these issues.

Regarding the competing issue and your suggestion to change the logout/restart logic: I've created a new image according to your proposal: `voyz/ibeam:0.4.0-rc3`. Please have a look at this branch to verify if the changes reflect what you've outlined: 
https://github.com/Voyz/ibeam/commit/4e35ec4f3dd798d36253f8c33e4f7533fb493073

Let me know how it goes 👍

**Comment by DanielHTpg** [comment]
@Voyz Thank you for the quick update of ibeam. I'll start using the new image and report back if issues occurs.

**Comment by JackD111** [comment]
@Voyz Thank you for the quick update of ibeam. I'll start using the new image and report back if issues occurs.

**Comment by alex1999Tra** [comment]
> Great stuff @alex1999Tra thanks for following up. Glad to hear you've had a month of smooth runtime! Which image are you using?

I am using voyz/ibeam:0.4.0-rc3

**Comment by JackD111** [comment]
@Voyz I think there is a problem with the new competing logic. I'm running  `voyz/ibeam:0.4.0-rc4` and the gatetway had some issues resulting in a competing state. IBeam dind't recognize the competing state. I had a look at the new logic and might have found something. I'm not much of a python guy but it seems that the return signature of https://github.com/Voyz/ibeam/blob/4e35ec4f3dd798d36253f8c33e4f7533fb493073/ibeam/src/gateway_client.py#L171 only returns a tuple of 3 booleans while https://github.com/Voyz/ibeam/blob/4e35ec4f3dd798d36253f8c33e4f7533fb493073/ibeam/src/http_handler.py#L40 returns 4. Dunno if that could cause the `get_status` to only get 3 out of the 4 boolean values.

I've also noticed, that the handling of true `competing` value is not correctly handling it. When `"competing": true` we need to send the `logout` request and than poll the `iserver/auth/status` endpoint until it retuns a 200 stauts code and `"authenticated": true`. Once we're authenticated we check for `competing`. If it's competing after the logout, only than do we want to send the `iserver/reauthenticate` request since that only seems to work shortly after a logout. Without a logout I never was able to loose the competing state when sending the reauth request.

Would appreciat if you can have another look at this when you have some time.

**Comment by Voyz** [comment]
Thanks for the feedback @JackD111, the discrepancy you found between the `(bool, bool, bool)` and `(bool, bool, bool, bool)` shouldn't cause any issues, but it's good to have it corrected nevertheless.

----

As for your further observations:

>  When `"competing": true` we need to send the `logout`

You'd need to clarify this a bit as this isn't what the current logic does. We currently send a `logout` when we try to authenticate and after successfully authenticating the status still shows `"authenticated": false`. This would previously cause the `Gateway session active but not authenticated` message that everyone is seeing, but now we also do the logout/reauth logic.

So the question is - at which point do you expect the _competing leading to logout_ logic you describe here happen?

----

>  and than poll the `iserver/auth/status`

Just to clarify, we actually call `/v1/api/tickle` as it gives a fuller response than `iserver/auth/status`, but the result is the same.

----

> we need to send the `logout` request and than poll the `iserver/auth/status` endpoint until it retuns a 200 stauts code and `"authenticated": true`

Once we call `logout` the API will never return `"authenticated": true` as it is logged out. We'd need to let IBeam authenticate again first.

----

>  Once we're authenticated we check for `competing`. If it's competing after the logout, only than do we want to send the `iserver/reauthenticate` request since that only seems to work shortly after a logout.

Unless I misunderstand your suggestion this is currently happening. Upon each maintenance after the Gateway startup, if the Gateway is:

1. Not running - do nothing and attempt to start Gateway on the next maintenance
2. Running, not authenticated, and without an active session - authenticate. Then if the session is still not authenticated, repeat the whole logic.
3. Running, not authenticated, with an active session but competing - call `reauthenticate`
4. Authenticated and not-competing - do nothing, everything is in order

Would you imagine it happening differently?

----

Apologies for the authentication logic having grown to be a bit spaghetti - it's handling more and more cases that caused the simple booleans to not suffice. I'm going to rewrite it a little to make it a bit more readable, bear with me.

Once again, thanks for the feedback! 🙏 Voy

**Comment by Voyz** [comment]
I've replaced the `(bool, bool, bool, bool)` logic with a `Status` object that should make the logic more readable. You can see the most recent version of your proposed logic here: https://github.com/Voyz/ibeam/compare/v0.4.0...reauthentication-v2

**Comment by JackD111** [comment]
@Voyz Thanks for the cleaner update with the new Status object. I've had another look and I think the only thing that needs change is the following part:
https://github.com/Voyz/ibeam/blob/90c086939bc856bd7e228e6fc137ea8202a8d687/ibeam/src/gateway_client.py#L130-L134
Here it should actually call the logout method. So the branch would execute when it's authenticated but competing. This would need a logout without the return at the end but it should rather just continue with doing the authentication again and  https://github.com/Voyz/ibeam/blob/90c086939bc856bd7e228e6fc137ea8202a8d687/ibeam/src/gateway_client.py#L164-L167 would than take care of a authenticated & competing state after the new login which than fixes possible empty brokerage account response.

**Comment by Voyz** [comment]
@JackD111 Could you clarify: Would you call `logout` instead of `reauthenticate`? Or before/after it?

**Comment by JackD111** [comment]
@Voyz Sometime after competing gets solved or a reauth we get the empty brokerage account response. Only a `reauthenticate` **very soon after** a `logout` seems to fix that so we want to first `logout`, than let IBeam authenticate again and than if it's authed but competing we want to call the `reauthenticate`.

Essentialy these lines https://github.com/Voyz/ibeam/blob/90c086939bc856bd7e228e6fc137ea8202a8d687/ibeam/src/gateway_client.py#L130-L138 should look like this

  ```
if status.session:
    if status.competing:
      _LOGGER.info('Competing Gateway session found, logging out...')
      self.restart()
    else:
      _LOGGER.info('Gateway session found but not authenticated, authenticating...')
else:
  _LOGGER.info('No active sessions, logging in...')
```
The rest after is fine

**Comment by Voyz** [comment]
Thanks for clarifying - can do, I'll get it together when I find a minute 👍

**Comment by Voyz** [comment]
@JackD111 try `voyz/ibeam:0.4.0-rc5` with the recently proposed changes

**Comment by JackD111** [comment]
@Voyz Your new update came just in time with both my paper and live account loosing connections. IBeam was able to re-establish the connection without competing but than the brokerage account responses were empty. I updated to rc5 and manually caused a logout with postman and after IBeam logged in again it was competing. The new logic than worked and restarted as expected and sent the reauthenticate request which fixed the empty brokerage response:
![image](https://user-images.githubusercontent.com/3951120/148563277-9f351c66-d9f3-4f21-8896-64e87ce0a05b.png)
Thanks for the quick update. I'll keep monitoring this and hopefully that empty brokerage response problem will be a thing of the past.

**Comment by JackD111** [comment]
@Voyz Looks like I celebrated to early :( My paper trading instance went crazy after I manually sent a logout request. It just kept logging out and reauthing the whole time:
![image](https://user-images.githubusercontent.com/3951120/148572048-ceda82fb-75f5-40f8-b5a7-b6a17e9ed3ed.png)
~16:57 was around when I sent the logout request.

I think the mess comes from returning here in the code:
https://github.com/Voyz/ibeam/blob/2ff6e6c65c2b28ae0edd100a38f9d1fc9ac1faaf/ibeam/src/gateway_client.py#L131-L136

I don't think we need that return and can just continue with the auth again after the logout, kinda like so:
```
            if status.session:
                if status.competing:
                    _LOGGER.info('Competing Gateway session found, reauthenticating...')
                    self.restart()
                else:
                  _LOGGER.info('Gateway session found but not authenticated, authenticating...')
            else:
                _LOGGER.info('No active sessions, logging in...')


            success, shutdown = self._authenticate()
            _LOGGER.info(f'Authentication process {"succeeded" if success else "failed"}')

```

**Comment by Voyz** [comment]
Just updated `rc5` with that return statement commented out @JackD111 let me know if that helps 👍

**Comment by JackD111** [comment]
Deleted the old image and pulled the new one. Same issues still persists. I checked the timestamps furhter and the logs and I think we need a sleep timer of maybe ~15-20 seconds.
![image](https://user-images.githubusercontent.com/3951120/148577151-ee7c30cf-a2c0-4cf5-9084-10921cec00a9.png)
At 17:40:16 you can see, that the restart was completed after the competing state, and we authenticated but it was still competing. Then the reauth request is sent but this request itself only triggers the reauth async
https://github.com/Voyz/ibeam/blob/2ff6e6c65c2b28ae0edd100a38f9d1fc9ac1faaf/ibeam/src/gateway_client.py#L164-L167
One second later the `try_authenticating` gets executed again, probably by the maintance. In that one second the reauth didn't even have time yet to complete so it was still competing and then it just startes logging out and stays stuck in the loop. I suggest a slepp timer before the return at https://github.com/Voyz/ibeam/blob/2ff6e6c65c2b28ae0edd100a38f9d1fc9ac1faaf/ibeam/src/gateway_client.py#L164-L167
probably 15-20 seconds to give the reauth process some time to complete

**Comment by Voyz** [comment]
@JackD111 thanks for the suggestion, just updated the `rc5` with the timeout after that reauthenticate call, configurable through IBEAM_RESTART_WAIT variable, 15 seconds by default

**Comment by Voyz** [comment]
hey @JackD111 how is that recent `rc5` working for you?

**Comment by JackD111** [comment]
@Voyz Oh damn, I didn't see the commented that you updated `rc5 ` again after my last comment. Been running `rc4` until now. Will update now and report later.

**Comment by Voyz** [comment]
Hey @JackD111 - just wondering if you'd have any observations to share by now?

**Comment by JackD111** [comment]
@Voyz The re-auth part with the new delay seems to do it. Since my last reply all worked great. Funnly enough, my paper trader had an issue this morning. After authenticating it lost the auth after a while and than had password errors, which don't really make sense to me:
![image](https://user-images.githubusercontent.com/3951120/153838610-7f8f6e32-dbb3-42d7-bf7d-f56befd8c434.png)
I've noticed this happen maybe 2-3 times in the last months. Really wouldn't know why this happens but it's not really an issue relating to the re-auth.
I waited an hour after this password error and re-started the container. The re-auth flow worked fine than:
![image](https://user-images.githubusercontent.com/3951120/153839134-d8d97d71-dd3b-45a0-a0d6-4593a350f963.png)

**Comment by Voyz** [comment]
Glad to hear things seem to have improved since then @JackD111 👍

Yes, I saw another user reporting the password error recently. This seems to be another little caveat of using IBKR, things like this happen sometimes 🤷‍♂️ I'd suggest you reach out to IBKR support in that regard.

Are you happy to close this issue or is there something else you'd want to discuss here?

**Comment by JackD111** [comment]
@Voyz Yeah, I'd say for now this issue is resolved. I haven't had any re-auths in my logs but since the latest change the IB gateway has also been running stable, so there was no reason for re-auths.

**Comment by Voyz** [comment]
Great to heat, thanks for the follow up @JackD111 👍 Feel free to reopen this issue if you'd like to continue the discussion
