### ISSUE TITLE
Interactive Brokers Account requirements

### ISSUE THREAD

**Issue by jonathonbattista** [Voyz/ibeam#48]
Hello!
I have been trying to use ibeam with a paper Account via IBKR API but keep getting inconsistent results with the gateway.

Obviously I want everything to work with the Paper Account first before trading with a Live Account.

I have reached out to IBKR support multiple times and each time they tell me I am missing something that wasnt specified in the Gateway API documentation.

For example:
- You cannot use a IBKR Lite Account with the API; you must upgrade to a IBKR Pro account (even though they are both free?)
- You must have at least $300 in the account for the API to function properly (including the Paper Account?)

These are the types of prerequisites that should be explicitly documented because an inconsistent API is an unusable API.

So I wanted to see what everyone else's IBKR Account setup is, if you have the API working consistently, and if I am missing anything.

Thanks!

**Comment by Voyz** [comment]
Hi @jonathonbattista thanks for sharing your question! 😊 Since this is related to IBKR account setup and not to IBeam directly I'm going to close this issue as unrelated - sorry. I'd encourage you to post the same question on https://www.reddit.com/r/interactivebrokers/ if you haven't already, or write to IBKR support directly. Keep in mind that Pro account is free if you satisfy certain monthly trading requirements. I'm not able to share my account setup with you at this time - again, sorry. Happy to help you with any IBeam related questions if you'd have any 👍 Once again, apologies I cannot help you with this matter 😔 Voy
