### ISSUE TITLE
Disable auto login for the docker image

### ISSUE THREAD

**Issue by umerebryx** [Voyz/ibeam#57]
I am trying to setup the docker image in a way that multiple users can login to the gateway using the login page. 
Currently the flow is that users provide their credentials in env variables, is there a way I can disable the auto login functionality when the docker image starts and just expose the login point which users can use to login themselves? The idea is multiple users will be logging in by themselves and then my bot can do the trading on their behalf. 

Would really appreciate your help. If you can point me in the direction how I will go about it I can make the changes or open separate branch. Thanks for the amazing tool!

**Comment by JackD111** [comment]
This wouldn't work since the IBKR gateway doesn't support concurrent users. You need one gateway instance per user. This would mean you need to create one ibeam instance per user.

**Comment by umerebryx** [comment]
@JackD111, yes I am spinning a new docker container for every user. I am providing the bot as a service. If you can point me int the direction how I can start a new container instance without passing the credentials that would solve my problem. Thanks

**Comment by JackD111** [comment]
You'd have to fork ibeam and change the code to not auto login. But like I mentioned before, the IBKR gateway ist not stable and need re-logins every couple of hours. This doesn't make using IBeam feasable without auto login.

**Comment by Voyz** [comment]
Thanks for outlining your use case @umerebryx and for leaving some useful suggestions @JackD111 👍

This in fact is doable with the recent `v0.4.0` image without having to rebuild anything. You need to override the Docker command IBeam uses to start, and run it with `-s` flag, ie.:

```posh
bash -c "python ibeam_starter.py -s ; sleep infinity"
```


Therefore, while by default you'd run it as:

```posh
docker run --env IBEAM_ACCOUNT=your_account123 --env IBEAM_PASSWORD=your_password123 -p 5000:5000 voyz/ibeam:0.4.0-rc5
```

In order to only start the Gateway and maintain the container with the Gateway running, call:

```posh
docker run --env IBEAM_ACCOUNT=your_account123 --env IBEAM_PASSWORD=your_password123 -p 5000:5000 voyz/ibeam:0.4.0-rc5 bash -c "python ibeam_starter.py -s ; sleep infinity"
```

The `; sleep infinity` ensures the container won't exit after the Gateway is started.

Note that even though you don't perform authentication, you'll still need to provide some dummy values for `IBEAM_ACCOUNT` and `IBEAM_PASSWORD`, as IBeam expect these as input by default and will not work otherwise.

Let me know if that helps 😊

**Comment by umerebryx** [comment]
@Voyz , that is exactly what I was looking for. Thanks a lot. I will close this thread. 🙏

**Comment by Voyz** [comment]
Happy to hear @umerebryx! Take care 😊
