### ISSUE TITLE
Gateway Error with TLS certificate

### ISSUE THREAD

**Issue by elaamrani** [Voyz/ibeam#58]
**Describe the bug**
I created both .pem and .jks certificate files and modified conf.yaml in both _sslCert_ and _sslPwd_ fields. I mounted .pem, .jks and .yaml files in /srv/inputs folder. When I run the gateway, I got the following error:
`Failed to verify the self-signed certificate. This could mean your self-generated .jks certificate and password are not correctly provided in Inputs Directory or listed in conf.yaml.`

**To Reproduce**
1. Build a custom Docker image
FROM voyz/ibeam:0.4.0-rc5
COPY inputs/ /srv/inputs/
VOLUME ["/srv/inputs/"]
2. Run container
3. Check logs

**Expected behavior**
Working connection in the same way when I do not provide certificates

**Environment**
IBeam version: 0.4.0-rc5
Docker image or standalone: 0.4.0-rc5
Python version (standalone users only): 3.8
OS: Debian Linux

**Additional context**
The connection works when I do not not modify conf.yaml fields and do not provide .pem and .jks files

**Suggest a Fix**
NA

**Comment by Voyz** [comment]
Thanks for the detailed report @elaamrani 👍 Let me first ask:

1. You're building your own IBeam image - I wonder why? You know you can provide the certificates by mounting them during `docker run` instead of doing `COPY inputs/ /srv/inputs/`?
2. > I created both .pem and .jks certificate files

     Could you paste the commands used (cover the credentials) to generate these certificates?
3. Is there any errors or warnings when generating the certificates?

**Comment by Voyz** [comment]
Hey @elaamrani I'm going to close this issue due to lack of activity. Feel free to reopen it if you'd like to continue the discussion 👍
