### ISSUE TITLE
proxyRemoteHost URL wrangling 

### ISSUE THREAD

**Issue by victory4software** [Voyz/ibeam#59]
**Describe the feature**
We are facing some issues with the authentication process with IBKR servers and temporarly we fixing it manually by change the IBKR internal url from   proxyRemoteHost: "https://api.ibkr.com" to   proxyRemoteHost: "https://2.api.ibkr.com"  or   proxyRemoteHost: "https://1.api.ibkr.com"

**Expected interaction**
Are you able to make the changing of this URL dynamically keep changing in case we are not able to authenticate the session.

**Comment by Voyz** [comment]
Hey @victory4software thanks for suggesting this enhancement 👍

In all fairness, this is clearly a load-balancing issue that I imagined that IBKR would have fixed in the past half a year that everyone has been seeing and reporting this issue. So the answer is yes, it can probably be done, although ideally we shouldn't have to do this.

In either case I think that it is technically doable, however it is non-trivial. To do this correctly we'd have to:

1. Stop the Gateway
2. Read the conf.yaml file
3. Correctly recognise and wrangle the servers' URL - this may be different for different users
4. Write back to conf.yaml
5. Start the Gateway
6. Attempt authentication to check if it helped

There's a risk of erroneously modifying the conf.yaml which is why I was trying to avoid this method until it's last resort. We have been developing a number of alternative fixes that are less risky. 

1. Which IBeam image are you currently running? 
2. Have you tried the `v0.4.0-rc5` or `v0.4.0-rc6`?

**Comment by victory4software** [comment]
I want to thank you for the quick reply.
I really appreciate your effort on that project.

I am using voyz/ibeam:lates  I think this image created on 2021-06-21 14:30:25

I will try the versions that you have mentioned and I will let you know.

**Comment by Voyz** [comment]
Hey @victory4software just wondering if you'd have any updates on how things are going on your end?

**Comment by victory4software** [comment]
Hi Voyz

 Thanks for reaching out.

Actually, I tried again each time is different issue.
But it is not your project issues it is from IBKR.
I opened a tickets with them and they replied to me that this project is
still under development.

So I changed my project to us the IBKR twz instead of their web portal. It
is much better.

Regards
Thanks
Victor

**Comment by Voyz** [comment]
Thanks for the follow up @victory4software - glad to hear you found your way around with TWS. Take care! 😊
